version: "3.8"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend_rust
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://admin:I98gw2zKiEn8iMov@budgetflowdb.anhdnhq.mongodb.net/?appName=BudgetFlowDB
      - PORT=3000
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - FRONTEND_ENV=${FRONTEND_ENV:-local}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  mongo-data:
